### ISSUE TITLE
Authentication in UWP app

### ISSUE THREAD

**Issue by Robelind** [OneDrive/onedrive-sdk-csharp#127]
I'm using the following code to authenticate:
`var oneDriveClient = OneDriveClientExtensions.GetClientUsingWebAuthenticationBroker(
                         "[app id]",
                         new []{"onedrive.readonly"});`
`AccountSession session = await oneDriveClient.AuthenticateAsync();`

After several seconds, a window is displayed saying:

> We're unable to complete your request. Microsoft account is experiencing technical problems.

**Comment by Forceh91** [comment]
I'm having the same issue as well. Have you managed to figure this out?

**Comment by Robelind** [comment]
No, hoping for an answer in the coming week.

**Comment by Forceh91** [comment]
Things seem to be working now.

**Comment by ginach** [comment]
@Robelind, have you associated your app with the store?

**Comment by Robelind** [comment]
Yes, I have associated the app with the store.

**Comment by programmersommer** [comment]
I have also associate my app with Store, but when I run 
```
   var scopes = new[] { "onedrive.readwrite", "onedrive.appfolder", "wl.signin" };
   IOneDriveClient cl = OneDriveClientExtensions.GetClientUsingOnlineIdAuthenticator(scopes);
   AccountSession session = await cl.AuthenticateAsync();
```
I am getting exception "Task was cancelled"

**Comment by ginach** [comment]
@programmersommer, are you trying to authenticate the user via a background task? Also, is this still happening for you?

@Forceh91, glad it's working now. Seems Microsoft account was actually having technical problems for you.

@Robelind, apologies since I misunderstood which authentication method you were using based on the subsequent issue responses. How is your app configured in the dev portal? Does your app ID look like a GUID or like a hex number?

**Comment by programmersommer** [comment]
No. I have not used background task. It's ok now. Thanks!

**Comment by cdmayer** [comment]
If anyone has remaining issues please reopen.
