### ISSUE TITLE
Copy and replace

### ISSUE THREAD

**Issue by msimecek** [OneDrive/onedrive-sdk-csharp#138]
When coping files on OneDrive using **Copy(newFileName, itemDestinationReference)**, it works for the first time (new file is created), but when running again (with the destination file already present) it ends with error.

With regular upload you can use the @name.conflictBehavior: "replace", which doesn't work with copy. Is there any other to overcome this other that checking if the file exists, deleting it and then coping?

**Comment by cdmayer** [comment]
That's not currently supported in the API. The Copy API is still in Preview, so that may be added in the future, but no guarantees.

A workaround would be to send a Delete request to the path where you want your file to go, and catch any NotFound errors. Definitely not ideal because it's 2 requests, but it should work for now.

**Comment by msimecek** [comment]
Thank you.
