### ISSUE TITLE
Possible to use AuthenticationContext

### ISSUE THREAD

**Issue by kevitra** [OneDrive/onedrive-sdk-csharp#215]
Is it possible to use the Azure AD AuthenticationContext in some manner to create a OneDrive SDK object?

In our app we currently authorize with:
AuthenticationContext authContext = await authContext.AcquireTokenAsync(graphResourceId, clientId, redirectUri, new PlatformParameters(PromptBehavior.Never));

//need provider
var oneDriveClient = new OneDriveClient("https://api.onedrive.com/v1.0", <provider> );

I've seen the examples with Msa and Adal but we are wondering if we can use what we currently have.

Thanks

**Comment by daboxu** [comment]
hi @kevitra , I think the [ADALAuthenticationProvider](https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/blob/master/src/OneDrive.Sdk.Authentication.Desktop/Business/AdalAuthenticationProvider.cs#L65) under our MSAAuthProvider should work for you because it allows you pass in an AuthenticationContext object. Give it a shot and let me know if you have any problems.

**Comment by daboxu** [comment]
feel free to reopen it if you have any question.
