### ISSUE TITLE
Is there a step by step guide for how to use the latest SDK in UWP Apps?

### ISSUE THREAD

**Issue by dmitrymal** [OneDrive/onedrive-sdk-csharp#238]
I tried to follow one of your examples (e.g. https://github.com/OneDrive/graph-sample-photobrowser-uwp) but it is 8 months old and not working. Besides, it uses old libraries like Microsoft.Identity.Client  (1.0.304142221-alpha) and requires a ClientId (whereas other samples on the internet say that you don't need a ClientId for Store Apps). So, what is the recommended ('the right') way?

Most of the examples on the Web are old (using the old version of the SDK) or don't work. **Is there a doc that describes a simple step by step guide to how to integrate OneDrive SDK in UWP apps?**

I am looking for something similar to one of these links:
https://msdn.microsoft.com/en-us/library/dn631826.aspx
https://msdn.microsoft.com/en-us/magazine/mt632271.aspx

**Comment by nitinphansalkar** [comment]
@dmitrymal : The following link is the updated Photobrowser Auth file. This works with current 1.1.0-preview version of Microsoft.Identity.Client

https://github.com/microsoftgraph/uwp-csharp-connect-sample/blob/master/Microsoft-Graph-UWP-Connect-SDK/AuthenticationHelper.cs

**Comment by dmitrymal** [comment]
The comment from @nitinphansalkar does **not** answer any questions asked in the original post. It has nothing to do with OneDrive and only references the authentication helper which is still using a preview version with the following warning: _"During the preview we may make changes to the API, internal cache format, and other mechanisms of this library... This may impact your application... For instance, a change to the cache format may impact your users, such as requiring them to sign in again. An API change may require you to update your code"_

I just want to add that we are trying to work on a REAL APP. We are not tinkering or playing with technology (which we do too, but not in this case). So far, we could not find a recommended official guide to how to integrate with OneDrive using the latest SDK. 

We would appreciate any **useful** reference/link that could help us move forward.

Thank you.

**Comment by nitinphansalkar** [comment]
@dmitrymal I am also a REAL APP developer and using (in a very limited way) OneDriveClient in my UWP app that is live on Store. App uses OneDriveClientExtensions for auth however that is no more supported and this new mechanism of Graph Client is introduced for the Auth. So I am making these changes.
I have been posting similar queries (step-by-step guidance) for using OneDrive in UWP app since last year or so. I have posted queries on Github and SO; however haven't got any direct answer (I call it spoon feeding!). So I understand your frustration. I have been constantly searching for the info and updating my Live app accordingly with appropriate warning messages to the user. It is sad that unlike other MSDN help there is no direct help available on OneDrive+UWP (with C#) and the reason is obvious - the technology is still WIP at Microsoft end.
So there are two options: 1. keep quiet till the Production Version of all associated technologies is released 2. Implement the Betas with appropriate warnings to the user.
I have been following second option with understanding users.

Thanks.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
