### ISSUE TITLE
Project Abandoned? 

### ISSUE THREAD

**Issue by VladimirAkopyan** [OneDrive/onedrive-sdk-csharp#250]
This project appears abandoned. What is the recommended package to use now to access onedrive from DotNet?

**Comment by Mogikan** [comment]
I also have this question. It is not compatible with latest Microsoft.Graph.Core. Migration to .net standard from Profile111 is also necessary.

**Comment by Mogikan** [comment]
Had to remove the following code from Request classes in order to compile it against latest graph.core. this.SdkVersionHeaderPrefix = "onedrive"; They removed this property from BaseRequest class and it's no longer available. This property is added to request header and used for Telemetry, so it's safe to remove it.

**Comment by Mogikan** [comment]
Finally decided to publish my changes (.net standard 2.0, can be used in .net core, works with latest graph.core) in case someone need it: https://github.com/Mogikan/onedrive-sdk-csharp

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
