### ISSUE TITLE
Silenlogin for Xamarin.Android

### ISSUE THREAD

**Issue by NPadrutt** [OneDrive/onedrive-sdk-csharp#84]
I use xamarin to port my app to android and IOS. For that I've written a authentication provider who uses xamarin auth.
You can see the code here: https://github.com/Apply-Solutions/MoneyManager/blob/master/Src/MoneyManager.Droid/Src/AndroidAuthenticationProvider.cs

 Currently I have to login every time I wanna access onedrive. My expectation was, that when I request the code, that the sdk will be able to get a refresh code withouth sign in again.

On Windows this works without any issue when I use the GetUniversalClient extension.
Do I have to implement something special for that?

**Comment by ginach** [comment]
GetUniversalClient is using the OnlineIdAuthenticator Windows API to log the user in. This uses the MSA connected to the machine for login automatically. It doesn't support multiple accounts in that scenario.

When working outside that API things work a bit differently as you also need to know which account is signing in. Since you're using OAuth2Authenticator you have a couple options:

- Use the account store functionality built into that API. Accounts can be [stored and retrieved using the functionality off AccountStore.Create()](https://components.xamarin.com/gettingstarted/xamarin.auth). Since you're implementing your own IAuthenticationProvider you could have the logic there to look up the account and decide what to do based on what is returned.
- Use the CredentialCache for caching. The CredentialCache is an in-memory cache that is modeled after [caching in ADAL](http://www.cloudidentity.com/blog/2013/10/01/getting-acquainted-with-adals-token-cache/). There's a GetCacheBlob method that will return the byte array representation of the cache for the app to store. That byte array can be passed into a cache constructor to re-initialize the cache. When you authenticate, AuthenticationProvider will look to see if there's already a credential with the app ID + user ID + account type of the authentication call and use that information, if it can, to authenticate requests. For example, if there's a refresh token for that user it will be used to retrieve a new access token. The user ID is important as it tells authentication which user to log in. If it doesn't know that information it'll have to prompt the user since all models other than OnlineIdAuthenticator allow a user to log in with any account.

Also, looking at your code, it's important to call out the difference between the authorization code and refresh token. Authenticating with the code flow requires 2 steps:

1. Prompt the user to sign in, redirect to the app with a ?code=authorization_code param.
2. Redeem the authorization code via an API call for an access token.

The authorization code is only valid for a short period of time. A refresh token, on the other hand, is returned with the access token in step 2 of the above if the wl.offline_access scope is requested. Your authentication provider is currently only doing step 1 of the above. The refresh token is the one that is valid for a year and is used for silent re-auth.

**Comment by NPadrutt** [comment]
Thanks Gina for your great answer! =)
I guess all my questions are answered with that :)

**Comment by devtag** [comment]
Hi Gina, can you please provide a sample how to implement that in Xamarin.iOS? Thanks
