### ISSUE TITLE
Trying to create a folder with same name twice does not throw exception

### ISSUE THREAD

**Issue by kinex** [OneDrive/onedrive-sdk-csharp#91]
I have an unit test which checks that trying to create the same subfolder twice should throw an exception. Here is the code which creates the folder (I call this twice):

`var folderToCreate = new Item { Name = "1", Folder = new Folder() };`
`var item = await this.OneDriveClient.Drives[this.DriveId].Items[this.Id].Children.Request().AddAsync(folderToCreate).ConfigureAwait(false);`

Earlier an exception was thrown, now it doesn't throw any exception. The second call doesn't seem to do anything (it doesn't even replace the existing folder if it's not empty). Is this some planned change, SDK issue or server side issue?

**Comment by ginach** [comment]
Thanks for reporting this, looks like a service bug. I've [moved the issue](https://github.com/OneDrive/onedrive-api-docs/issues/323) over to the documentation repo.

**Comment by rgregg** [comment]
Copying my response here for tracking purposes:

This is by design. The first time you POST, we return 201 Created. The second time, we return 200 OK (indicating that the item already existed). In a RESTful API design, you've asked (through POST) that we ensure that a folder named "1" exist. That request didn't change between the first request and the second, the end result (a folder named "1" exists) is still true.

If you want to change the behavior to fail in the second request, you can add a property to the item to control the behavior:
```
{
"name": "1",
"folder": {},
"@name.conflictBehavior": "fail"
}
```

Using this body for the POST message will ensure that you get the result you expected.
