### ISSUE TITLE
unable to authenticate on Xamarin Android Mobile App.

### ISSUE THREAD

**Issue by maheshmitkari** [OneDrive/onedrive-sdk-csharp#92]
HI 

I am trying to use OneDrive SDK CSharp on Xamarin Android Platform. since Xamarin was mentioned on OneDrive Dev site i tried to added Nugget and it worked. 

i tried following code as give in Documentation. 

``try
            {               
                string RETURN_URL = "https://login.live.com/oauth20_desktop.srf";
                
                var oneDriveClient = OneDriveClient.GetMicrosoftAccountClient(
                                               appId: AppData.OneDriveClientID,
                                               returnUrl: RETURN_URL,
                                               scopes: new[] { "wl.signin", "wl.offline_access", "onedrive.readwrite" },                                             
                                               clientSecret: AppData.OneDriveClientSecretV1                                              
                                               );

                var accountSession = await oneDriveClient.AuthenticateAsync();               
            }
            catch(Exception ex)
            {

            }`
`

But its not working , App does not redirect me to any login screen. I am directly getting Exception with Error message as  "Failed to retrieve a valid authentication token for the user."

I have created App on portal and got valid Client id and Client Secret, i also marked app as Mobile/Desktop app on account developer center portal.

can someone please help me resolve this issue ? 

Thank You,
Regards
Mahesh Mitkari

**Comment by ginach** [comment]
There is no default authentication implementation for Xamarin. The error you're seeing is because the authentication provider doesn't have an IWebAuthenticationUi implementation to prompt UI to the user. There are 2 main options for authenticating in Xamarin:

1. Create an IWebAuthenticationUi implementation for processing the OAuth UI and pass that in to GetMicrosoftAccountClient.
2. Implement your own IAuthenticationProvider for authentication. [Xamarin.Auth](https://components.xamarin.com/gettingstarted/xamarin.auth) has an OAuth2Authenticator that makes authentication on Xamarin fairly easy.

**Comment by ronnie-kleinfeld** [comment]
Hi
I'm trying to implement the IWebAuthenticationUi for Xamarin
do you have an example?

**Comment by cdmayer** [comment]
Check out the Windows Forms implementation: https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/src/OneDriveSdk.WindowsForms/Web/FormsWebAuthenticationUi.cs

**Comment by devtag** [comment]
@ginach could you please provide a sample how to implement the IAuthenticationProvider in Xamarin.iOS? How can I get the provider for OneDriveClient from OAuth2Authenticator?
